name: Swift

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test (iOS Simulator)
      run: |
        xcodebuild test \
          -scheme SenseKit \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -skipPackagePluginValidation
